# Generated by Django 4.2.24 on 2025-10-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursebuilder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours_per_day',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='day',
            name='video_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
